name: CI Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  static-code-analysis:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install NPM packages
        run: npm install --prefix src

      - name: Run linting
        run: npm run test-lint --prefix src

  unit-testing:
    runs-on: ubuntu-latest

    steps:
      - name: running unit test
        run: npm run test-unit --prefix src
