name: CI Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  static-code-analysis:
    runs-on: ubuntu-latest

    steps:
      - name: List directory contents
        run: |
          echo "Current directory:"
          ls -la
          echo "src directory (if it exists):"
          ls -la src || echo "src directory not found"

      - name: Run linting
        run: npm run test-lint
