name: CI Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  setup:
    uses: ./.github/workflows/shared.yml

  static-code-analysis:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Run linting
        run: npm run test-lint --prefix src

  unit-testing:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: running unit test
        run: npm run test-unit --prefix src
