name: CI Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  static-code-analysis:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: List directory contents after checkout
        run: |
          echo "Current directory after checkout:"
          ls -la
          echo "src directory (if it exists):"
          ls -la src || echo "src directory not found"

      - name: Run linting
        run: npm run test-lint --prefix src
