name: CI Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  static-code-analysis:
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/actions/setup
      - name: Run linting
        run: npm run test-lint --prefix src

  unit-testing:
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/actions/setup
      - name: Run unit tests
        run: npm run test-unit --prefix src
