name: CI Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  static-code-analysis:
    runs-on: ubuntu-latest

    steps:
      - name: Running static code analysis
        run: npm run test-lint
